const color = {
  main: {
    primary: {
      1: "#FF5623",
      2: "#F66C42",
      3: "#FF845F",
      4: "#FFA58A",
      5: "#FFEBE5",
    },
    secondary: {
      1: "#0094DE",
      2: "#19A5EB",
      3: "#3FB3ED",
      4: "#73C7F1",
      5: "#E2F5FF",
    },
  },
  status: {
    success: "#4ADE80",
    info: "#246BFD",
    warning: "#FACC15",
    error: "#F75555",
    disabled: "#D8D8D8",
    disabledButton: "#EA8262",
  },
  greyscale: {
    50: "#fafafa",
    100: "#f5f5f5",
    200: "#eeeeee",
    300: "#E0E0E0",
    400: "#BDBDBD",
    500: "#9E9E9E",
    600: "#757575",
    700: "#757575",
    800: "#424242",
    900: "#212121",
  },
  background: {
    green: "#F6FFFA",
    blue: "#F6FAFD",
    yellow: "#FFFEE0",
    red: "#FFF5F5",
    purple: "#FCF4FF",
    transparent: "rgba(33, 33, 33, 0.5)",
  },
  gradient: {
    gradientBlue: { x: "#246BFD", y: "#6F9EFF" },
    gradientSunsetOrange: { x: "#FE6F1F", y: "#FD954A" },
    gradientPurple: { x: "#6842FF", y: "#896BFF" },
    gradientGreen: { x: "#1AB65C", y: "#39E180" },
    gradientYellow: { x: "#FACC15", y: "#FFE580" },
  },
  dark: {
    dark1: "#181A20",
    dark2: "#1F222A",
    dark3: "#35383F",
  },
  red: "#F54336",
  pink: "#EA1E61",
  purple: "#9D28AC",
  deeppurple: "#673AB3",
  indigo: "#3F51B2",
  blue: "#1A96F0",
  lightblue: "#00A9F1",
  cyan: "#00BCD3",
  teal: "#009689",
  green: "#4AAF57",
  lightgreen: "#8BC255",
  lime: "#CDDC4C",
  yellow: "#FFEB4F",
  amber: "#FFC02D",
  orange: "#FF981F",
  deeporange: "#FF5726",
  brown: "#7A5548",
  bluegrey: "#607D8A",
  black: "#000000",
  white: "#FFFFFF",
  transparent: "transparent",
  current: "currentColor",
};

const colors = {
  // brand color
  primary1: color.main.primary[1],
  primary2: color.main.primary[2],
  primary3: color.main.primary[3],
  primary4: color.main.primary[4],
  primary5: color.main.primary[5],

  secondary1: color.main.secondary[1],
  secondary2: color.main.secondary[2],
  secondary3: color.main.secondary[3],
  secondary4: color.main.secondary[4],
  secondary5: color.main.secondary[5],

  // greyscale
  greyscale50: color.greyscale[50],
  greyscale100: color.greyscale[100],
  greyscale200: color.greyscale[200],
  greyscale300: color.greyscale[300],
  greyscale400: color.greyscale[400],
  greyscale500: color.greyscale[500],
  greyscale600: color.greyscale[600],
  greyscale700: color.greyscale[700],
  greyscale800: color.greyscale[800],
  greyscale900: color.greyscale[900],

  // status color
  success: color.status.success,
  error: color.status.error,
  warning: color.status.warning,
  info: color.status.info,
  disabled: color.status.disabled,
  disabledButton: color.status.disabledButton,

  // background
  backgroundGreen: color.background.green,
  backgroundRed: color.background.red,
  backgroundYellow: color.background.yellow,
  backgroundBlue: color.background.blue,
  backgroundPurple: color.background.purple,
  backgroundTransparent: color.background.transparent,

  // misc
  gradientBlueX: color.gradient.gradientBlue.x,
  gradientBlueY: color.gradient.gradientBlue.y,
  gradientSunsetOrangeX: color.gradient.gradientSunsetOrange.x,
  gradientSunsetOrangeY: color.gradient.gradientSunsetOrange.y,
  gradientGreenX: color.gradient.gradientGreen.x,
  gradientGreenY: color.gradient.gradientGreen.y,
  gradientPurpleX: color.gradient.gradientPurple.x,
  gradientPurpleY: color.gradient.gradientPurple.y,
  gradientYellowX: color.gradient.gradientYellow.x,
  gradientYellowY: color.gradient.gradientYellow.y,

  dark1: color.dark.dark1,
  dark2: color.dark.dark2,
  dark3: color.dark.dark3,
  red: color.red,
  pink: color.pink,
  purple: color.purple,
  deeppurple: color.deeppurple,
  indigo: color.indigo,
  blue: color.blue,
  lightblue: color.lightblue,
  cyan: color.cyan,
  teal: color.teal,
  green: color.green,
  lightgreen: color.lightgreen,
  lime: color.lime,
  yellow: color.yellow,
  amber: color.amber,
  orange: color.orange,
  deeporange: color.deeporange,
  brown: color.brown,
  bluegrey: color.bluegrey,

  black: color.black,
  white: color.white,
  transparent: color.transparent,
  current: color.current,
};

export default colors;
